### ISSUE TITLE
requiring iban.js from hardcoded path

### ISSUE THREAD

**Issue by Orppa** [mmjmanders/ng-iban#6]
ng-iban.js has 

this.IBAN = require("./..\\bower_components\\iban\\iban.js");

but this for sure doesn't work in every environment.
Everyone might not use bower_components for example.

**Comment by mmjmanders** [comment]
I used grunt-browserify; browserify means you can use NPM modules in the browser. But since iban.js is a Bower package and not an NPM module; I have to use de debowerify transformation. This is defined in the Gruntfile:
```js
browserify: {
  dist: {
    options: {
      transform: ['debowerify']
    },
    files: {
      '.tmp/ng-iban.js': '.tmp/ng-iban.js'
    }
  }
}
```

If you check the output `ng-iban.js` you see the following:
```js
this.IBAN = require("./..\\bower_components\\iban\\iban.js");
```

which is actually a reference to `ng-iban.js` on line 70: https://github.com/mmjmanders/ng-iban/blob/master/dist/ng-iban.js#L70

Therefore this works
