### ISSUE TITLE
dist-folder via npm install

### ISSUE THREAD

**Issue by LukasVice** [mmjmanders/ng-iban#9]
hi,
i would like to use ng-iban in my application by using npm install. unfortunately i don't receive the dist-folder. with bower all works fine, but i don't want to use bower. could you please help me?
thank you.

**Comment by mmjmanders** [comment]
It is in the lib folder; the dist is for bower; the lib for npm. I believe this is not a preferred way to work. I am in the process of refining the entire module.

**Comment by LukasVice** [comment]
yes, i tried the one in the lib folder, but i get an error saying the "require"-function is not defined...

**Comment by mmjmanders** [comment]
Can you please describe the steps so I can try to reproduce?

**Comment by filidorwiese** [comment]
I have the same issue. The file `ng-iban/lib/ng-iban.js` references to `require()`, which is not part of angular

**Comment by mmjmanders** [comment]
The .js file in the lib folder is for use with npm; you can only use this with tools like webpack or browserify.

**Comment by filidorwiese** [comment]
Ah yes, but not without :wink:

**Comment by LukasVice** [comment]
Since i don't want to use browserify or webpack just for ng-iban, isn't it possible to make it work with npm but without those tools?

**Comment by mmjmanders** [comment]
How are you planning on getting it in a frontend app? Then I recommend using the `bower` way.

**Comment by filidorwiese** [comment]
First off, thanks for this useful piece of code. However it could be improved by not having a dependency on webpack or browserify, which I personally don't use. Next to that, I've also ditched bower in favor of npm. The point is that how I choose to include ng-iban should be of no concern to it.

For now I'll stick to using version 0.4.0 of your library because that version does include a build version that doesn't depend on a module loader to offer `require()`.
